name: deploy static website to s3

on:
  push: 
    branches: [ main ]

jobs: 
  deploy: 
    name: upload website to s3
    runs-on: ubuntu latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
		with:
	      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 📦 Deploy files to S3
        run: aws s3 sync . s3://my-static-website-bhavesh --exclude ".git/*" --exclude ".github/*" --delete

      - name: ✅ Deployment Success Message
        run: echo "🎉 Website successfully deployed to S3!"

